/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buencortemvc;

import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class menuOpciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuOpciones.class.getName());

    /**
     * Creates new form menuOpciones
     */
    public menuOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGestionCli = new javax.swing.JButton();
        btnCRUDDetalleCita = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnEmpleadosGe = new javax.swing.JButton();
        btnCitasGe = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("MENU DE OPCIONES");

        btnGestionCli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGestionCli.setText("GESTION DE CLIENTES");
        btnGestionCli.addActionListener(this::btnGestionCliActionPerformed);

        btnCRUDDetalleCita.setText("GESTION DETALLE CITA");
        btnCRUDDetalleCita.addActionListener(this::btnCRUDDetalleCitaActionPerformed);

        btnPagos.setText("GESTION DE PAGOS");
        btnPagos.addActionListener(this::btnPagosActionPerformed);

        btnEmpleadosGe.setText("GESTION EMPLEADOS");
        btnEmpleadosGe.addActionListener(this::btnEmpleadosGeActionPerformed);

        btnCitasGe.setText("GESTION DE CITA");
        btnCitasGe.addActionListener(this::btnCitasGeActionPerformed);

        jButton2.setText("GESTION SERVICIO");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCRUDDetalleCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnEmpleadosGe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnCitasGe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionCli)
                .addGap(8, 8, 8)
                .addComponent(btnEmpleadosGe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnCitasGe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCRUDDetalleCita, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionCliActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "gestion de clientes");
        dashboard_clientes clientes=new dashboard_clientes();
        clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionCliActionPerformed

    private void btnCRUDDetalleCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDDetalleCitaActionPerformed
dashboard_detalleCita detalleCita = new dashboard_detalleCita();
        detalleCita.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCRUDDetalleCitaActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gestion de pagos");
        dashboard_pagos pagos = new dashboard_pagos();
        pagos.setLocationRelativeTo(null);
        pagos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnEmpleadosGeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosGeActionPerformed
        // TODO add your handling code here:
        dashboard_empleados emple=new dashboard_empleados();
        emple.setVisible(true);
    }//GEN-LAST:event_btnEmpleadosGeActionPerformed

    private void btnCitasGeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasGeActionPerformed
        // TODO add your handling code here:
        dashboard_citas cit=new dashboard_citas();
        cit.setVisible(true);
    }//GEN-LAST:event_btnCitasGeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dashboard_servicio ser=new dashboard_servicio();
        ser.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuOpciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDDetalleCita;
    public javax.swing.JButton btnCitasGe;
    public javax.swing.JButton btnEmpleadosGe;
    public javax.swing.JButton btnGestionCli;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
